
POST http://localhost:3000/api/user-roles/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoidXNlciIsIm5tVmVuZGVkb3IiOiJSRUdJTkFMRE8iLCJjZEVtcHJlc2FQdWJsaWMiOjExLCJjZFZlbmRlZG9yIjoxNSwiaWRFbXByZXNhIjoibm92YV9vcGNhbyIsImlkQ25waiI6IjEzNDI3MTM1MDAwMTgwIiwiY2RFcXVpcGUiOjEsIm5tRXF1aXBlIjoiR2VyZW5jaWEgR2VyYWwiLCJpZEVxdWlwZSI6IjEiLCJpZEVtYWlsIjoicmVnaW5hbGRvQG5vcGNhby5jb20uYnIiLCJkdEZlY2hhbWVudG8iOjI1LCJmZ0Z1bmNhbyI6MywiZmdSZXNwb25zYXZlbCI6dHJ1ZSwiZXhwaXJlc0luIjoxNzA4NDY3OTAyMjIxLCJ1c2VyUm9sZXMiOlsic2FsZXMucmV2ZW51ZS5hbGwiLCJzYWxlcy5wcm9maXQuYWxsIiwic2FsZXMubWFya3VwLmFsbCIsInNhbGVzLmNvbXBhcmF0aXZlLmFsbCIsInNhbGVzLmxpbmVhcml0eS5hbGwiLCJzYWxlcy5mYWN0b3J5LmFsbCIsInNhbGVzLmNhdGVnb3J5LmFsbCIsIm1hbmFnZV91c2VycyIsIm1hbmFnZV91c2Vycy5yb2xlcyJdLCJpYXQiOjE3MDcyNTgzMDIsImV4cCI6MTcwNzI1ODMwMn0.T3XFueDvA0UUK9z2pwQqCyJPVBDRF4KOmji3tw1THVU

{
  "cdPerfilAcesso": 2,
  "roles": ["sales.revenue"]
}