version: '2'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: 'doadmin'
      POSTGRES_PASSWORD: 'data@DATA@2019'
      POSTGRES_DB: 'bi'
    ports:
      - '5432:5432'
    volumes:
      - './db-data:/var/lib/postgresql/data'
